project_id = "rfwvemsjwytxxhwowpqh"

[functions.norman-chat]
verify_jwt = false

[functions.connect-integration]
verify_jwt = false

[functions.manage-company-integration]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-callback]
verify_jwt = false

[functions.google-calendar-api]
verify_jwt = false

[functions.google-drive-auth]
verify_jwt = false

[functions.google-drive-callback]
verify_jwt = false

[functions.google-drive-api]
verify_jwt = false

[functions.notion-api]
verify_jwt = false

[functions.submit-google-form]
verify_jwt = false

[functions.parse-google-form]
verify_jwt = false
