import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function generateStyledHTML(title: string, weekRange: string, content: string, generatedBy: string): string {
  // Convert markdown-like content to HTML
  let htmlContent = content
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Bullet points
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // Numbered lists
    .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
    // Paragraphs (double newlines)
    .replace(/\n\n/g, '</p><p>')
    // Single newlines within paragraphs
    .replace(/\n/g, '<br/>');

  // Wrap consecutive <li> items in <ul>
  htmlContent = htmlContent.replace(/((?:<li>.*?<\/li>\s*)+)/g, '<ul>$1</ul>');

  // RYG indicators
  htmlContent = htmlContent
    .replace(/🟢/g, '<span style="color:#22c55e;font-weight:bold;">🟢</span>')
    .replace(/🟡/g, '<span style="color:#eab308;font-weight:bold;">🟡</span>')
    .replace(/🔴/g, '<span style="color:#ef4444;font-weight:bold;">🔴</span>');

  const now = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>
<style>
  @page { size: A4; margin: 2cm; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
    color: #1a1a2e;
    line-height: 1.6;
    background: #ffffff;
    padding: 40px;
    max-width: 900px;
    margin: 0 auto;
  }
  .header {
    border-bottom: 3px solid #1a1a2e;
    padding-bottom: 20px;
    margin-bottom: 30px;
  }
  .header h1 {
    font-size: 28px;
    color: #1a1a2e;
    margin-bottom: 4px;
  }
  .header .subtitle {
    font-size: 16px;
    color: #64748b;
    margin-bottom: 2px;
  }
  .header .date {
    font-size: 13px;
    color: #94a3b8;
  }
  h1 { font-size: 22px; margin: 24px 0 12px; color: #1a1a2e; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
  h2 { font-size: 18px; margin: 20px 0 10px; color: #334155; }
  h3 { font-size: 15px; margin: 16px 0 8px; color: #475569; }
  p { margin: 8px 0; font-size: 14px; }
  ul { margin: 8px 0 8px 20px; }
  li { margin: 4px 0; font-size: 14px; }
  strong { color: #0f172a; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
  th { background: #f1f5f9; padding: 8px 12px; text-align: left; border: 1px solid #e2e8f0; font-weight: 600; }
  td { padding: 8px 12px; border: 1px solid #e2e8f0; }
  .footer {
    margin-top: 40px;
    padding-top: 16px;
    border-top: 1px solid #e2e8f0;
    font-size: 11px;
    color: #94a3b8;
    text-align: center;
  }
  @media print {
    body { padding: 0; }
    .header { page-break-after: avoid; }
  }
</style>
</head>
<body>
<div class="header">
  <h1>${title}</h1>
  <div class="subtitle">${weekRange}</div>
  <div class="date">Generated on ${now} by Duncan AI</div>
</div>
<div class="content">
  <p>${htmlContent}</p>
</div>
<div class="footer">
  Confidential — ${generatedBy} — Generated by Duncan Intelligence System
</div>
</body>
</html>`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY")!;

    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Missing authorization" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const body = await req.json();
    const { title, week_range, content, company_name } = body;

    if (!content || !title) {
      return new Response(JSON.stringify({ error: "title and content are required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const weekRange = week_range || "Weekly Executive Summary";
    const companyName = company_name || "Kabuni";

    // Generate styled HTML document
    const htmlDoc = generateStyledHTML(title, weekRange, content, companyName);
    const htmlBytes = new TextEncoder().encode(htmlDoc);

    // Build filename
    const safeTitle = title.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '_').slice(0, 60);
    const dateStr = new Date().toISOString().split('T')[0];
    const fileName = `${safeTitle}_${dateStr}.html`;
    const blobPath = `executive-summaries/${fileName}`;

    // Upload to Azure Blob Storage via the azure-blob-api function
    const formData = new FormData();
    const file = new File([htmlBytes], fileName, { type: "text/html" });
    formData.append("file", file);
    formData.append("action", "upload");
    formData.append("path", "executive-summaries");

    const uploadRes = await fetch(`${supabaseUrl}/functions/v1/azure-blob-api`, {
      method: "POST",
      headers: { Authorization: authHeader },
      body: formData,
    });

    if (!uploadRes.ok) {
      const err = await uploadRes.text();
      throw new Error(`Upload failed: ${err}`);
    }

    const uploadData = await uploadRes.json();

    // Build download URL through the proxy
    const downloadUrl = `${supabaseUrl}/functions/v1/azure-blob-api?action=download&path=${encodeURIComponent(blobPath)}`;

    return new Response(
      JSON.stringify({
        success: true,
        file_name: fileName,
        blob_path: blobPath,
        blob_url: uploadData.url,
        download_url: downloadUrl,
        message: `Executive summary "${title}" has been generated and saved. The document can be opened in any browser and printed as a PDF.`,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    console.error("Generate exec summary error:", err);
    return new Response(
      JSON.stringify({ error: err.message || "Internal error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
